In [1]:
import main_model

['LICENSE.md', 'tools', 'app2.py', 'requirements.txt', 'deploy', 'figure', 'utils', 'models', '__pycache__', 'cfg', 'yolov7.pt', 'README.md', 'scripts', 'app.py', 'inference', '.ipynb_checkpoints', 'traced_model.pt', 'testrun.ipynb', 'hubconf.py', 'data', 'runs']


/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [2]:
main_model.run('./static/files/frames/use007-730-2', './static/files/car/use007-730-2')

YOLOR 🚀 2022-12-7 torch 1.12.1 CPU



True
Fusing layers... 


[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.
Model Summary: 306 layers, 36905341 parameters, 6652669 gradients


RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
 Convert model to Traced-model... 
 traced_script_module saved! 
 model is traced! 



/opt/anaconda3/lib/python3.9/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


[[[ 52  30  17]
  [ 85  69  61]]

 [[126  81  35]
  [ 79  53  38]]]
Blue
<class 'numpy.ndarray'>
(11, 231) (803, 734)
<class 'numpy.ndarray'>
(503, 792, 3)
runs/detect/exp6/bus
1 bus, Done. (2215.4ms) Inference, (0.7ms) NMS
Done. (2017.3ms) Inference, (0.3ms) NMS
Done. (2439.8ms) Inference, (0.4ms) NMS
Done. (2158.0ms) Inference, (0.3ms) NMS
Done. (2021.5ms) Inference, (0.4ms) NMS
Done. (1730.5ms) Inference, (0.3ms) NMS
 The image with the result is saved in: runs/detect/exp6/zidane.jpg
Done. (12.687s)
